# Generated by Django 5.1.7 on 2025-03-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0004_reponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
